import { FormEvent, useEffect, useState } from 'react'
import { Activity, Bell, ChevronRight, HeartPulse, Home, MapPin, Menu, MoreHorizontal, Settings, ShieldCheck, Users } from 'lucide-react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import './styles.css'
import { createRoot } from 'react-dom/client'

declare global { interface Window { google?: { accounts: { id: { initialize: (config: unknown) => void; renderButton: (element: HTMLElement, config: unknown) => void } } } } }

const trend = [{day:'Mon', value:72},{day:'Tue',value:86},{day:'Wed',value:80},{day:'Thu',value:91},{day:'Fri',value:84},{day:'Sat',value:89},{day:'Sun',value:88}]
const nav = [{label:'Overview', icon:Home},{label:'Patients',icon:Users},{label:'Activities',icon:Activity},{label:'Alerts',icon:Bell},{label:'Location',icon:MapPin},{label:'Reports',icon:HeartPulse}]

function App() {
  const [active, setActive] = useState('Overview')
  const [user, setUser] = useState<AuthUser | null>(() => { const saved = localStorage.getItem('neurox-user'); return saved ? JSON.parse(saved) as AuthUser : null })
  if (!user) return <SignIn onAuthenticated={setUser}/>
  const signOut = () => { localStorage.removeItem('neurox-token'); localStorage.removeItem('neurox-refresh-token'); localStorage.removeItem('neurox-user'); setUser(null) }
  return <div className="app-shell">
    <aside><div className="brand"><span className="logo">N</span><span>neuro<span>X</span></span></div><nav>{nav.map(({label,icon:Icon})=><button key={label} className={active===label?'selected':''} onClick={()=>setActive(label)}><Icon size={20}/>{label}{label==='Alerts'&&<i>2</i>}</button>)}</nav><div className="sidebar-bottom"><button><Settings size={20}/>Settings</button><button className="user" onClick={signOut} title="Sign out"><div className="avatar">{initials(user.name)}</div><div><b>{user.name}</b><small>Caregiver · Sign out</small></div><MoreHorizontal size={20}/></button></div></aside>
    <main><header><div><p className="eyebrow">CAREGIVER PORTAL</p><h1>Good morning, {user.name.split(' ')[0]}</h1><p className="subtitle">Here’s how your family members are doing today.</p></div><div className="header-actions"><button className="icon-button"><Bell size={21}/><em/></button><button className="profile">{initials(user.name)}</button></div></header>
      <section className="stats"><Stat icon={<Users/>} label="Active patients" value="3" detail="All connected today" tone="blue"/><Stat icon={<Activity/>} label="Activities today" value="8 / 10" detail="2 remaining" tone="green"/><Stat icon={<Bell/>} label="Pending alerts" value="2" detail="1 needs attention" tone="amber"/><Stat icon={<ShieldCheck/>} label="Safety status" value="All safe" detail="3 of 3 at home" tone="mint"/></section>
      <section className="grid"><article className="panel patient"><div className="panel-head"><div><p className="eyebrow">YOUR PATIENT</p><h2>Maya Devi</h2><p>72 years · Assamese</p></div><button className="quiet">View profile <ChevronRight size={16}/></button></div><div className="patient-body"><div className="maya-avatar">MD</div><div className="patient-info"><div className="safe"><ShieldCheck size={18}/> At Home · Safe</div><p><MapPin size={16}/> Last updated 2 minutes ago</p><p><Activity size={16}/> Today’s activity: <b>Memory Match</b></p></div></div><div className="reminder"><div className="reminder-icon"><Bell size={19}/></div><div><b>Next reminder</b><p>Hydration · 10:30 AM</p></div><button>View</button></div></article>
        <article className="panel performance"><div className="panel-head"><div><p className="eyebrow">THIS WEEK</p><h2>Activity performance</h2><p>Supportive engagement trend</p></div><button className="quiet">Report <ChevronRight size={16}/></button></div><div className="chart-top"><div><strong>88%</strong><span>average completion</span></div><span className="up">↑ 6% from last week</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#4d73d9" stopOpacity=".26"/><stop offset="1" stopColor="#4d73d9" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="value" stroke="#4168d5" strokeWidth={3} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div></article>
      </section>
      <section className="lower"><article className="panel alerts"><div className="panel-head"><div><p className="eyebrow">NEEDS ATTENTION</p><h2>Recent alerts</h2></div><button className="quiet">View all <ChevronRight size={16}/></button></div><Alert color="orange" title="Medication reminder missed" detail="Maya Devi · 9:00 AM" label="Routine"/><Alert color="red" title="Expected return time exceeded" detail="Ravi Das · 8 minutes ago" label="High"/></article><article className="panel location"><div className="panel-head"><div><p className="eyebrow">LOCATION</p><h2>Last known location</h2></div><span className="online">● Online</span></div><div className="map"><div className="roads a"/><div className="roads b"/><div className="zone"><span>Maya Devi</span><MapPin fill="currentColor"/></div><div className="map-label">Home safe zone<br/><small>GPS accuracy ±18 m</small></div></div></article></section>
      <p className="disclaimer">NeuroX provides supportive insights from activity data. It does not diagnose or treat medical conditions.</p>
    </main><button className="mobile-menu"><Menu/></button></div>
}
type AuthUser = { id: string; name: string; email: string; role: string }
type AuthResponse = { access_token: string; refresh_token: string; user: AuthUser }
const apiUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000'
const initials = (name: string) => name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase()
function SignIn({onAuthenticated}:{onAuthenticated:(user:AuthUser)=>void}) {
  const [email, setEmail] = useState('anita@neurox.demo'), [password, setPassword] = useState('NeuroXDemo!2026'), [error, setError] = useState(''), [loading, setLoading] = useState(false)
  const finish = (data: AuthResponse) => { localStorage.setItem('neurox-token', data.access_token); localStorage.setItem('neurox-refresh-token', data.refresh_token); localStorage.setItem('neurox-user', JSON.stringify(data.user)); onAuthenticated(data.user) }
  const submit = async (event:FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const response = await fetch(`${apiUrl}/auth/login`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}); const data = await response.json(); if(!response.ok) throw new Error(data.detail ?? 'Unable to sign in.'); finish(data) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to sign in.') } finally { setLoading(false) } }
  useEffect(() => { const clientId = import.meta.env.VITE_GOOGLE_CLIENT_ID; if (!clientId) return; const script = document.createElement('script'); script.src='https://accounts.google.com/gsi/client'; script.async=true; script.onload=()=>{ window.google?.accounts.id.initialize({client_id:clientId, callback:async ({credential}:{credential:string})=>{ try { const response=await fetch(`${apiUrl}/auth/google`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({credential})}); const data=await response.json(); if(!response.ok) throw new Error(data.detail); finish(data) } catch(err) { setError(err instanceof Error ? err.message : 'Google sign-in failed.') } }}); const target=document.getElementById('google-button'); if(target) { target.textContent=''; window.google?.accounts.id.renderButton(target,{theme:'outline',size:'large',width:360,text:'continue_with'}) } }; document.head.appendChild(script); return ()=>script.remove() }, [])
  return <main className="auth-page"><section className="auth-card"><div className="brand"><span className="logo">N</span><span>neuro<span>X</span></span></div><p className="eyebrow">CAREGIVER PORTAL</p><h1>Welcome back</h1><p className="subtitle">Sign in to view supportive activity and safety information.</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={8} required/></label>{error&&<p className="auth-error">{error}</p>}<button className="auth-submit" disabled={loading}>{loading?'Signing in…':'Sign in'}</button></form><div className="or"><span/>or continue with<span/></div><div id="google-button" className="google-placeholder">Google sign-in appears after you set VITE_GOOGLE_CLIENT_ID.</div><p className="auth-foot">Demo: anita@neurox.demo / NeuroXDemo!2026</p></section></main>
}
function Stat({icon,label,value,detail,tone}:{icon:React.ReactNode,label:string,value:string,detail:string,tone:string}) {return <article className="stat"><div className={`stat-icon ${tone}`}>{icon}</div><p>{label}</p><h2>{value}</h2><small>{detail}</small></article>}
function Alert({color,title,detail,label}:{color:string,title:string,detail:string,label:string}) {return <div className="alert-row"><span className={`dot ${color}`}/><div><b>{title}</b><p>{detail}</p></div><span className={`tag ${color}`}>{label}</span><ChevronRight size={18}/></div>}
export default App
createRoot(document.getElementById('root')!).render(<App />)
